//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTunes.Duplicate.Gui.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\David\\Downloads")]
        public string SourceDirectory {
            get {
                return ((string)(this["SourceDirectory"]));
            }
            set {
                this["SourceDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M:\\Music")]
        public string DestinationDirectory {
            get {
                return ((string)(this["DestinationDirectory"]));
            }
            set {
                this["DestinationDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>'</string>
  <string>’</string>
  <string>`</string>
  <string>.</string>
  <string>,</string>
  <string>(Radio)</string>
  <string>(Main)</string>
  <string>(PO Clean Edit)</string>
  <string>(Clean)</string>
  <string>(Original)</string>
  <string>(Original Mix Edit)</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TitleFilters {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TitleFilters"]));
            }
            set {
                this["TitleFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int TimeDifferenceInSec {
            get {
                return ((int)(this["TimeDifferenceInSec"]));
            }
            set {
                this["TimeDifferenceInSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ft</string>
  <string>Ft</string>
  <string>FT</string>
  <string>ft.</string>
  <string>Ft.</string>
  <string>FT.</string>
  <string>feat.</string>
  <string>Feat.</string>
  <string>feat</string>
  <string>Feat</string>
  <string>featuring</string>
  <string>Featuring</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RemoveFromArtist {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RemoveFromArtist"]));
            }
            set {
                this["RemoveFromArtist"] = value;
            }
        }
    }
}
